// ISO 3166-1 alpha-2 → English country name.
// Used for partner URLs that require the country name in English (e.g. Airalo).
const COUNTRY_NAMES_EN = {
  AF: 'afghanistan', AL: 'albania', DZ: 'algeria', AS: 'american-samoa', AD: 'andorra',
  AO: 'angola', AI: 'anguilla', AQ: 'antarctica', AG: 'antigua-and-barbuda', AR: 'argentina',
  AM: 'armenia', AW: 'aruba', AU: 'australia', AT: 'austria', AZ: 'azerbaijan',
  BS: 'bahamas', BH: 'bahrain', BD: 'bangladesh', BB: 'barbados', BY: 'belarus',
  BE: 'belgium', BZ: 'belize', BJ: 'benin', BM: 'bermuda', BT: 'bhutan',
  BO: 'bolivia', BA: 'bosnia-and-herzegovina', BW: 'botswana', BR: 'brazil', BN: 'brunei',
  BG: 'bulgaria', BF: 'burkina-faso', BI: 'burundi', KH: 'cambodia', CM: 'cameroon',
  CA: 'canada', CV: 'cape-verde', KY: 'cayman-islands', CF: 'central-african-republic', TD: 'chad',
  CL: 'chile', CN: 'china', CO: 'colombia', KM: 'comoros', CG: 'congo', CD: 'democratic-republic-of-the-congo',
  CK: 'cook-islands', CR: 'costa-rica', HR: 'croatia', CU: 'cuba', CW: 'curacao',
  CY: 'cyprus', CZ: 'czech-republic', DK: 'denmark', DJ: 'djibouti', DM: 'dominica',
  DO: 'dominican-republic', EC: 'ecuador', EG: 'egypt', SV: 'el-salvador', GQ: 'equatorial-guinea',
  ER: 'eritrea', EE: 'estonia', SZ: 'eswatini', ET: 'ethiopia', FJ: 'fiji',
  FI: 'finland', FR: 'france', GF: 'french-guiana', PF: 'french-polynesia', GA: 'gabon',
  GM: 'gambia', GE: 'georgia', DE: 'germany', GH: 'ghana', GI: 'gibraltar',
  GR: 'greece', GL: 'greenland', GD: 'grenada', GP: 'guadeloupe', GU: 'guam',
  GT: 'guatemala', GG: 'guernsey', GN: 'guinea', GW: 'guinea-bissau', GY: 'guyana',
  HT: 'haiti', HN: 'honduras', HK: 'hong-kong', HU: 'hungary', IS: 'iceland',
  IN: 'india', ID: 'indonesia', IR: 'iran', IQ: 'iraq', IE: 'ireland',
  IM: 'isle-of-man', IL: 'israel', IT: 'italy', CI: 'ivory-coast', JM: 'jamaica',
  JP: 'japan', JE: 'jersey', JO: 'jordan', KZ: 'kazakhstan', KE: 'kenya',
  KI: 'kiribati', KW: 'kuwait', KG: 'kyrgyzstan', LA: 'laos', LV: 'latvia',
  LB: 'lebanon', LS: 'lesotho', LR: 'liberia', LY: 'libya', LI: 'liechtenstein',
  LT: 'lithuania', LU: 'luxembourg', MO: 'macao', MG: 'madagascar', MW: 'malawi',
  MY: 'malaysia', MV: 'maldives', ML: 'mali', MT: 'malta', MH: 'marshall-islands',
  MQ: 'martinique', MR: 'mauritania', MU: 'mauritius', MX: 'mexico', FM: 'micronesia',
  MD: 'moldova', MC: 'monaco', MN: 'mongolia', ME: 'montenegro', MS: 'montserrat',
  MA: 'morocco', MZ: 'mozambique', MM: 'myanmar', NA: 'namibia', NR: 'nauru',
  NP: 'nepal', NL: 'netherlands', NC: 'new-caledonia', NZ: 'new-zealand', NI: 'nicaragua',
  NE: 'niger', NG: 'nigeria', NU: 'niue', KP: 'north-korea', MK: 'north-macedonia',
  NO: 'norway', OM: 'oman', PK: 'pakistan', PW: 'palau', PS: 'palestine',
  PA: 'panama', PG: 'papua-new-guinea', PY: 'paraguay', PE: 'peru', PH: 'philippines',
  PL: 'poland', PT: 'portugal', PR: 'puerto-rico', QA: 'qatar', RE: 'reunion',
  RO: 'romania', RU: 'russia', RW: 'rwanda', BL: 'saint-barthelemy', SH: 'saint-helena',
  KN: 'saint-kitts-and-nevis', LC: 'saint-lucia', MF: 'saint-martin', PM: 'saint-pierre-and-miquelon',
  VC: 'saint-vincent-and-the-grenadines', WS: 'samoa', SM: 'san-marino', ST: 'sao-tome-and-principe',
  SA: 'saudi-arabia', SN: 'senegal', RS: 'serbia', SC: 'seychelles', SL: 'sierra-leone',
  SG: 'singapore', SX: 'sint-maarten', SK: 'slovakia', SI: 'slovenia', SB: 'solomon-islands',
  SO: 'somalia', ZA: 'south-africa', KR: 'south-korea', SS: 'south-sudan', ES: 'spain',
  LK: 'sri-lanka', SD: 'sudan', SR: 'suriname', SE: 'sweden', CH: 'switzerland',
  SY: 'syria', TW: 'taiwan', TJ: 'tajikistan', TZ: 'tanzania', TH: 'thailand',
  TL: 'timor-leste', TG: 'togo', TK: 'tokelau', TO: 'tonga', TT: 'trinidad-and-tobago',
  TN: 'tunisia', TR: 'turkey', TM: 'turkmenistan', TC: 'turks-and-caicos-islands', TV: 'tuvalu',
  UG: 'uganda', UA: 'ukraine', AE: 'united-arab-emirates', GB: 'united-kingdom', US: 'united-states',
  UY: 'uruguay', UZ: 'uzbekistan', VU: 'vanuatu', VA: 'vatican-city', VE: 'venezuela',
  VN: 'vietnam', VG: 'british-virgin-islands', VI: 'us-virgin-islands', WF: 'wallis-and-futuna',
  YE: 'yemen', ZM: 'zambia', ZW: 'zimbabwe',
};

/** Returns lowercase, kebab-case English country name by ISO 3166-1 alpha-2, or null. */
export function countryNameEn(code) {
  if (!code) return null;
  return COUNTRY_NAMES_EN[code.toUpperCase()] || null;
}