// AUTO-GENERATED for the Tolgee in-context LAB (TRIP-127). Throwaway.
// Snapshot of the landing Hero strings so the lab renders offline,
// before the Chrome extension / live Tolgee data kicks in.
export const staticData = {
  "en": {
    "landing.hero.h1_a": "Your whole trip.",
    "landing.hero.h1_b_accent": "One",
    "landing.hero.h1_c": "beautiful plan.",
    "landing.hero.lede": "Build multi-city itineraries, plan together, track budgets in every currency, and let Triplanio handle the boring parts.",
    "landing.hero.cta_primary": "Start Planning",
    "landing.hero.cta_secondary": "See how it works",
    "landing.hero.trust_free": "Free to start",
    "landing.hero.trust_no_card": "No credit card",
    "landing.hero.trust_languages": "Multilingual platform",
    "landing.mockup.trips": "Trips",
    "landing.mockup.this_trip": "This trip",
    "landing.mockup.trip_title": "Iberia - Summer '26",
    "landing.mockup.subtitle": "Jul 12 → Jul 23 · 3 cities · 4 travelers",
    "landing.mockup.tab_timeline": "Timeline",
    "landing.mockup.tab_calendar": "Calendar",
    "landing.mockup.tab_map": "Map",
    "landing.mockup.nights_4": "Lisbon · 4 nights",
    "landing.mockup.nights_2": "Porto · 2 nights",
    "landing.mockup.nights_5": "Barcelona · 5 nights",
    "landing.mockup.other_trip_1": "Japan in cherry season",
    "landing.mockup.other_trip_2": "Patagonia trek",
    "landing.mockup.tag_flight": "Flight",
    "landing.mockup.tag_hotel": "Hotel",
    "landing.mockup.tag_activity": "Activity",
    "landing.mockup.tag_transfer": "Transfer",
    "landing.mockup.checkin": "check-in",
    "landing.mockup.day1": "Sat · Jul 12",
    "landing.mockup.day2": "Sun · Jul 13",
    "landing.mockup.day3": "Wed · Jul 16",
    "landing.float.trip_budget": "Trip budget",
    "landing.float.leave_at_title": "Leave at 14:10",
    "landing.float.leave_at_sub": "Train to Porto, 30 min from hotel",
    "landing.city.lisbon": "Lisbon",
    "landing.city.porto": "Porto",
    "landing.city.barcelona": "Barcelona"
  },
  "es": {
    "landing.hero.h1_a": "Todo tu viaje.",
    "landing.hero.h1_b_accent": "Un",
    "landing.hero.h1_c": "plan precioso.",
    "landing.hero.lede": "Crea itinerarios entre varias ciudades, planea en equipo y lleva el presupuesto en cualquier divisa.",
    "landing.hero.cta_primary": "Empezar a planear",
    "landing.hero.cta_secondary": "Ver cómo funciona",
    "landing.hero.trust_free": "Gratis para empezar",
    "landing.hero.trust_no_card": "Sin tarjeta de crédito",
    "landing.hero.trust_languages": "Plataforma multilingüe",
    "landing.mockup.trips": "Viajes",
    "landing.mockup.this_trip": "Este viaje",
    "landing.mockup.trip_title": "Iberia - Verano '26",
    "landing.mockup.subtitle": "12 jul → 23 jul · 3 ciudades · 4 viajeros",
    "landing.mockup.tab_timeline": "Línea de tiempo",
    "landing.mockup.tab_calendar": "Calendario",
    "landing.mockup.tab_map": "Mapa",
    "landing.mockup.nights_4": "Lisboa · 4 noches",
    "landing.mockup.nights_2": "Oporto · 2 noches",
    "landing.mockup.nights_5": "Barcelona · 5 noches",
    "landing.mockup.other_trip_1": "Japón en temporada de cerezos",
    "landing.mockup.other_trip_2": "Trek por la Patagonia",
    "landing.mockup.tag_flight": "Vuelo",
    "landing.mockup.tag_hotel": "Hotel",
    "landing.mockup.tag_activity": "Actividad",
    "landing.mockup.tag_transfer": "Traslado",
    "landing.mockup.checkin": "check-in",
    "landing.mockup.day1": "Sáb · 12 jul",
    "landing.mockup.day2": "Dom · 13 jul",
    "landing.mockup.day3": "Mié · 16 jul",
    "landing.float.trip_budget": "Presupuesto del viaje",
    "landing.float.leave_at_title": "Sal a las 14:10",
    "landing.float.leave_at_sub": "Tren a Oporto, 30 min del hotel",
    "landing.city.lisbon": "Lisboa",
    "landing.city.porto": "Oporto",
    "landing.city.barcelona": "Barcelona"
  },
  "ru": {
    "landing.hero.h1_a": "Вся твоя поездка.",
    "landing.hero.h1_b_accent": "Один",
    "landing.hero.h1_c": "красивый план.",
    "landing.hero.lede": "Стройте маршруты по нескольким городам, планируйте вместе, ведите бюджет в любой валюте - Triplanio возьмёт рутину на себя.",
    "landing.hero.cta_primary": "Начать планировать",
    "landing.hero.cta_secondary": "Как это работает",
    "landing.hero.trust_free": "Бесплатный старт",
    "landing.hero.trust_no_card": "Без банковской карты",
    "landing.hero.trust_languages": "Мультиязычная платформа",
    "landing.mockup.trips": "Поездки",
    "landing.mockup.this_trip": "Эта поездка",
    "landing.mockup.trip_title": "Иберия - лето '26",
    "landing.mockup.subtitle": "12 июля → 23 июля · 3 города · 4 путешественника",
    "landing.mockup.tab_timeline": "Таймлайн",
    "landing.mockup.tab_calendar": "Календарь",
    "landing.mockup.tab_map": "Карта",
    "landing.mockup.nights_4": "Лиссабон · 4 ночи",
    "landing.mockup.nights_2": "Порту · 2 ночи",
    "landing.mockup.nights_5": "Барселона · 5 ночей",
    "landing.mockup.other_trip_1": "Япония в сезон сакуры",
    "landing.mockup.other_trip_2": "Трек по Патагонии",
    "landing.mockup.tag_flight": "Перелёт",
    "landing.mockup.tag_hotel": "Отель",
    "landing.mockup.tag_activity": "Активность",
    "landing.mockup.tag_transfer": "Трансфер",
    "landing.mockup.checkin": "заезд",
    "landing.mockup.day1": "Сб · 12 июля",
    "landing.mockup.day2": "Вс · 13 июля",
    "landing.mockup.day3": "Ср · 16 июля",
    "landing.float.trip_budget": "Бюджет поездки",
    "landing.float.leave_at_title": "Выходите в 14:10",
    "landing.float.leave_at_sub": "Поезд в Порту, 30 мин от отеля",
    "landing.city.lisbon": "Лиссабон",
    "landing.city.porto": "Порту",
    "landing.city.barcelona": "Барселона"
  }
};
