import React, { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/api/supabaseClient';
import { useI18n } from '@/lib/i18n/I18nContext';
import { Btn, Dialog, Severity, Skeleton } from '@/design/index';
import { captureAndUploadRouteMap } from '@/lib/map/captureMap';

// Shared trip "Share" dialog. Two parts:
//   1. Public read-only link (ensureShareToken) — unchanged.
//   2. Social share card (TRIP-193) — a server-rendered story/post PNG with the
//      trip route + key numbers + QR, generated by the render-share-card edge
//      function and cached by content hash. Preview is shown inline; the user
//      can Download or (on mobile) share via the native sheet.
export default function ShareDialog({ trip, open, onOpenChange, visits = [], transfers = [] }) {
  const { t, lang } = useI18n();
  const [shareUrl, setShareUrl] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  // --- social card state ---
  const [format, setFormat] = useState('story');
  const [cardUrl, setCardUrl] = useState('');
  const [cardLoading, setCardLoading] = useState(false);
  const [cardCode, setCardCode] = useState(''); // '', 'error', 'rate_limited', 'no_transit_cities'

  useEffect(() => {
    if (!trip?.id) return;
    let cancelled = false;
    setLoading(true);
    setError('');
    supabase.functions.invoke('ensureShareToken', { body: { tripId: trip.id } })
      .then(({ data, error: invokeErr }) => {
        if (cancelled) return;
        if (invokeErr) { console.error('ensureShareToken error:', invokeErr); setError(t('trip.link_error')); return; }
        const token = data?.shareToken || data?.token;
        if (token) {
          setShareUrl(`${window.location.origin}/public/trip/${trip.id}?t=${token}`);
        } else {
          setError(t('trip.link_error'));
        }
      })
      .catch((err) => { if (!cancelled) { console.error('ensureShareToken error:', err); setError(t('trip.link_error')); } })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [trip?.id]);

  // Capture the live route map → upload to share-maps → render the card with it.
  // If capture/upload fails, map_path is null and the server falls back to its
  // own map, so a card is always produced. `isCancelled` guards against stale
  // results when the dialog closes or the format changes mid-flight.
  const generateCard = useCallback((fmt, isCancelled) => {
    if (!trip?.id) return;
    setCardLoading(true);
    setCardCode('');
    setCardUrl('');
    (async () => {
      let mapPath = null;
      try {
        mapPath = await captureAndUploadRouteMap(trip.id, { visits, transfers, format: fmt, scheme: 'DARK', lang });
      } catch (e) { console.error('map capture/upload failed', e); }
      if (isCancelled?.()) return;
      try {
        const { data, error: invokeErr } = await supabase.functions.invoke(
          'render-share-card', { body: { trip_id: trip.id, format: fmt, lang, map_path: mapPath } },
        );
        if (isCancelled?.()) return;
        if (invokeErr) { console.error('render-share-card error:', invokeErr); setCardCode('error'); }
        else if (data?.code) setCardCode(data.code);
        else if (data?.url) setCardUrl(data.url);
        else setCardCode('error');
      } catch (err) {
        if (!isCancelled?.()) { console.error('render-share-card error:', err); setCardCode('error'); }
      } finally {
        if (!isCancelled?.()) setCardLoading(false);
      }
    })();
  }, [trip?.id, lang, visits, transfers]);

  // (Re)generate the preview when the dialog opens or the format changes.
  useEffect(() => {
    if (!open || !trip?.id) return undefined;
    let cancelled = false;
    generateCard(format, () => cancelled);
    return () => { cancelled = true; };
  }, [open, trip?.id, format, generateCard]);

  function copyLink() {
    if (!shareUrl) return;
    navigator.clipboard?.writeText(shareUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  async function downloadCard() {
    if (!cardUrl) return;
    try {
      const res = await fetch(cardUrl);
      const blob = await res.blob();
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `triplanio-${format}.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(a.href);
    } catch (e) { console.error('download card failed', e); }
  }

  async function shareCard() {
    if (!cardUrl) return;
    try {
      const res = await fetch(cardUrl);
      const blob = await res.blob();
      const file = new File([blob], `triplanio-${format}.png`, { type: 'image/png' });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file] });
      } else {
        downloadCard();
      }
    } catch (e) {
      // AbortError = user dismissed the share sheet; ignore.
      if (e?.name !== 'AbortError') console.error('share card failed', e);
    }
  }

  const ratio = format === 'story' ? '9 / 16' : '4 / 5';
  const cardErrorMsg = cardCode === 'rate_limited' ? t('share.card_rate_limited')
    : cardCode === 'no_transit_cities' ? t('share.card_no_cities')
    : cardCode === 'error' ? t('share.card_error') : '';

  return (
    <Dialog
      title={t('share.dialog_title')}
      icon="share"
      size="sm"
      open={open}
      onOpenChange={onOpenChange}
      foot={<Btn variant="ghost" onClick={() => onOpenChange?.(false)}>{t('common.close')}</Btn>}
    >
      <div className="muted t-body" style={{ marginBottom: 18 }}>{t('trip.share_desc')}</div>
      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
        <input className="input" readOnly value={loading ? '' : shareUrl} placeholder={loading ? t('share.generating') : ''} style={{ flex: 1 }} onClick={(e) => e.target.select()} />
        <Btn variant="primary" icon="check" loading={loading} onClick={copyLink} disabled={!shareUrl}>
          {loading ? t('share.generating') : (copied ? t('trip.link_copied') : t('share.copy'))}
        </Btn>
      </div>
      {error && <div style={{ marginTop: 10 }}><Severity level="error">{error}</Severity></div>}

      {/* --- Social share card (TRIP-193) --- */}
      <div style={{ marginTop: 24, borderTop: '1px solid var(--line)', paddingTop: 18 }}>
        <div className="t-title">{t('share.card_title')}</div>
        <div className="muted t-body" style={{ margin: '4px 0 14px' }}>{t('share.card_desc')}</div>

        <div style={{ display: 'flex', gap: 8, marginBottom: 14 }}>
          <Btn variant={format === 'story' ? 'primary' : 'ghost'} onClick={() => setFormat('story')}>{t('share.card_story')}</Btn>
          <Btn variant={format === 'post' ? 'primary' : 'ghost'} onClick={() => setFormat('post')}>{t('share.card_post')}</Btn>
        </div>

        <div style={{ display: 'flex', gap: 16, alignItems: 'flex-start' }}>
          <div style={{ width: 200, aspectRatio: ratio, borderRadius: 14, overflow: 'hidden', background: 'var(--surface)', flex: 'none', border: '1px solid var(--line)' }}>
            {cardLoading
              ? <Skeleton w="100%" h="100%" r={14} />
              : cardUrl
                ? <img src={cardUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                : null}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8, flex: 1 }}>
            <Btn variant="primary" icon="share" onClick={shareCard} disabled={!cardUrl || cardLoading} block>{t('share.card_share')}</Btn>
            <Btn variant="ghost" icon="download" onClick={downloadCard} disabled={!cardUrl || cardLoading} block>{t('share.card_download')}</Btn>
          </div>
        </div>

        {cardErrorMsg && (
          <div style={{ marginTop: 12 }}>
            <Severity level={cardCode === 'rate_limited' ? 'warning' : 'error'}>{cardErrorMsg}</Severity>
          </div>
        )}
      </div>
    </Dialog>
  );
}
