import React, { useState, useEffect, useRef } from 'react';
import { supabase } from '@/api/supabaseClient';
import { useI18n } from '@/lib/i18n/I18nContext';
import { Badge, Btn, Dialog, Severity, Skeleton } from '@/design/index';
import { renderCardMapPng, blobToDataUri, rasterizeSvgToPng } from '@/lib/map/captureMap';
import ShareMapPreview from './ShareMapPreview';
import './ShareDialog.css';

// Must match MAP_PLACEHOLDER in the render-share-card edge function (card_svg mode).
const MAP_PLACEHOLDER = '__SHARE_CARD_MAP__';

// A short retry to ride out a transient invoke failure (network / cold isolate).
// overlay and card_svg both return an SVG string; we retry only transient failures
// - a definitive app code (no_transit_cities) or a success returns immediately.
async function invokeCard(body, tries = 3) {
  let last;
  for (let attempt = 0; attempt < tries; attempt++) {
    // eslint-disable-next-line no-await-in-loop
    last = await supabase.functions.invoke('render-share-card', { body });
    // success (final card url OR overlay svg) or a definitive app code → done
    if (last?.data?.url || last?.data?.svg || last?.data?.code) return last;
    // eslint-disable-next-line no-await-in-loop
    if (attempt < tries - 1) await new Promise((r) => setTimeout(r, 800 * (attempt + 1)));
  }
  return last;
}

// Shared trip "Share" dialog. Two parts:
//   1. Public read-only link (ensureShareToken) — unchanged.
//   2. Social share card (TRIP-193) — a server-rendered story/post PNG with the
//      trip route + key numbers + QR, generated by the render-share-card edge
//      function and cached by content hash. Preview is shown inline; the user
//      can Download or (on mobile) share via the native sheet.
export default function ShareDialog({ trip, open, onOpenChange, visits = [], transfers = [] }) {
  const { t, lang } = useI18n();
  const [shareUrl, setShareUrl] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  // --- social card state ---
  const [format, setFormat] = useState('story');
  const [cardUrl, setCardUrl] = useState('');
  const [cardLoading, setCardLoading] = useState(false);
  const [cardCode, setCardCode] = useState(''); // '', 'error', 'no_transit_cities'
  const [stage, setStage] = useState('edit'); // 'edit' (compose map) | 'card' (final)
  const [overlay, setOverlay] = useState(null); // frame preview: { url, slot, w, h }
  const mapPreviewRef = useRef(null);
  const cardBlobUrlRef = useRef(null); // object URL of the browser-rendered PNG (revoke on replace)

  function revokeCardUrl() {
    if (cardBlobUrlRef.current) { URL.revokeObjectURL(cardBlobUrlRef.current); cardBlobUrlRef.current = null; }
  }

  useEffect(() => {
    if (!trip?.id) return;
    let cancelled = false;
    setLoading(true);
    setError('');
    supabase.functions.invoke('ensureShareToken', { body: { tripId: trip.id } })
      .then(({ data, error: invokeErr }) => {
        if (cancelled) return;
        if (invokeErr) { console.error('ensureShareToken error:', invokeErr); setError(t('trip.link_error')); return; }
        const token = data?.shareToken || data?.token;
        if (token) {
          setShareUrl(`${window.location.origin}/public/trip/${trip.id}?t=${token}`);
        } else {
          setError(t('trip.link_error'));
        }
      })
      .catch((err) => { if (!cancelled) { console.error('ensureShareToken error:', err); setError(t('trip.link_error')); } })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [trip?.id]);

  // Build the final card IN THE BROWSER (TRIP-193 Ф2): render the composed route
  // map at the card's real resolution, ask the edge only for the card SVG (fonts
  // embedded, map left as a placeholder), inject the map, rasterise SVG -> PNG.
  // No edge resvg -> the HTTP 546 cold-isolate failure cannot happen, and the map
  // is no longer capped to 600px.
  async function buildCard() {
    if (!trip?.id) return;
    setCardLoading(true);
    setCardCode('');
    revokeCardUrl();
    setCardUrl('');
    try {
      const comp = mapPreviewRef.current?.getComposition?.();
      const slot = overlay?.slot;
      const cardW = overlay?.w;
      const cardH = overlay?.h;
      if (!comp || !slot || !cardW || !cardH) throw new Error('preview not ready');

      const mapBlob = await renderCardMapPng({ visits, transfers, ...comp, width: slot.w, height: slot.h });
      if (!mapBlob) throw new Error('map render failed');
      const mapDataUri = await blobToDataUri(mapBlob);

      const { data, error: invokeErr } = await invokeCard({ trip_id: trip.id, format, lang, mode: 'card_svg' });
      if (invokeErr || !data?.svg) throw new Error('card svg failed');

      const svg = data.svg.split(MAP_PLACEHOLDER).join(mapDataUri);
      const pngBlob = await rasterizeSvgToPng(svg, data.width || cardW, data.height || cardH);
      const objUrl = URL.createObjectURL(pngBlob);
      cardBlobUrlRef.current = objUrl;
      setCardUrl(objUrl);
      setStage('card');
    } catch (e) {
      console.error('card build failed', e);
      setCardCode('error');
    } finally {
      setCardLoading(false);
    }
  }

  // Reset to the compose stage each time the dialog (re)opens; free any prior PNG.
  useEffect(() => {
    if (open) { setStage('edit'); revokeCardUrl(); setCardUrl(''); setCardCode(''); }
  }, [open]);

  // Free the last browser-rendered PNG object URL on unmount.
  useEffect(() => () => revokeCardUrl(), []);

  // Fetch the card FRAME as an SVG and render it IN THE BROWSER over the live map
  // (no server rasterisation - that intermittently blew the edge CPU limit and
  // left the preview a bare map). The frame's transparent hole reveals the map.
  useEffect(() => {
    if (!open || !trip?.id || stage !== 'edit') return undefined;
    let cancelled = false;
    setOverlay(null);
    invokeCard({ trip_id: trip.id, format, lang, mode: 'overlay' })
      .then(({ data, error: invokeErr }) => {
        if (cancelled || invokeErr || !data?.svg) return;
        setOverlay({ svg: data.svg, slot: data.slot, w: data.width, h: data.height });
      })
      .catch((e) => { if (!cancelled) console.error('overlay fetch failed', e); });
    return () => { cancelled = true; };
  }, [open, trip?.id, format, lang, stage]);

  function copyLink() {
    if (!shareUrl) return;
    navigator.clipboard?.writeText(shareUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  async function downloadCard() {
    if (!cardUrl) return;
    try {
      const res = await fetch(cardUrl);
      const blob = await res.blob();
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `triplanio-${format}.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(a.href);
    } catch (e) { console.error('download card failed', e); }
  }

  async function shareCard() {
    if (!cardUrl) return;
    try {
      const res = await fetch(cardUrl);
      const blob = await res.blob();
      const file = new File([blob], `triplanio-${format}.png`, { type: 'image/png' });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file] });
      } else {
        downloadCard();
      }
    } catch (e) {
      // AbortError = user dismissed the share sheet; ignore.
      if (e?.name !== 'AbortError') console.error('share card failed', e);
    }
  }

  const ratio = format === 'story' ? '9 / 16' : '4 / 5';
  const cardErrorMsg = cardCode === 'no_transit_cities' ? t('share.card_no_cities')
    : cardCode === 'error' ? t('share.card_error') : '';

  // Preview card in the chosen aspect ratio. Placement (left column on desktop,
  // under the title on mobile) is owned by .sc-preview in ShareDialog.css; the
  // status badge overlays its corner.
  const previewBox = {
    position: 'relative',
    height: 'min(46vh, 400px)', aspectRatio: ratio,
    borderRadius: 14, overflow: 'hidden',
    background: 'var(--surface)', border: '1px solid var(--line)',
  };
  const statusBadgeStyle = {
    position: 'absolute', top: 10, left: 10, color: '#fff',
    background: stage === 'edit' ? 'rgba(20,25,35,.65)' : 'var(--success)',
  };

  return (
    <Dialog
      title={t('share.dialog_title')}
      icon="share"
      size="wide"
      open={open}
      onOpenChange={onOpenChange}
      foot={<Btn variant="ghost" onClick={() => onOpenChange?.(false)}>{t('common.close')}</Btn>}
    >
      {/* 1. Public read-only link */}
      <div className="muted t-body" style={{ marginBottom: 12 }}>{t('trip.share_desc')}</div>
      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
        <input className="input" readOnly value={loading ? '' : shareUrl} placeholder={loading ? t('share.generating') : ''} style={{ flex: 1, minWidth: 0 }} onClick={(e) => e.target.select()} />
        <Btn variant="primary" size="sm" icon="check" loading={loading} onClick={copyLink} disabled={!shareUrl}>
          {loading ? t('share.generating') : (copied ? t('trip.link_copied') : t('share.copy'))}
        </Btn>
      </div>
      {error && <div style={{ marginTop: 10 }}><Severity level="error">{error}</Severity></div>}

      {/* 2. Social share card (TRIP-193). Layout owned by ShareDialog.css:
          desktop = map | [title, controls]; mobile = title, map, controls. */}
      <div className="sc-wrap">
        <div className="sc-card">
          <div className="sc-head">
            <div className="t-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              {t('share.card_title')}
              <Badge style={{ background: 'var(--brand-soft)', color: 'var(--brand)' }}>{t('share.card_new')}</Badge>
            </div>
            <div className="muted t-body sc-hint">
              {stage === 'edit' ? t('share.card_map_hint') : t('share.card_ready_desc')}
            </div>
          </div>

          <div className="sc-preview">
            <div style={previewBox}>
              {stage === 'edit'
                ? <ShareMapPreview key={format} ref={mapPreviewRef} visits={visits} transfers={transfers} lang={lang} overlaySvg={overlay?.svg} slot={overlay?.slot} cardW={overlay?.w} cardH={overlay?.h} />
                : (cardUrl
                  ? <img src={cardUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                  : <Skeleton w="100%" h="100%" r={14} />)}
              <Badge style={statusBadgeStyle}>{stage === 'edit' ? t('share.card_preview') : t('share.card_ready_badge')}</Badge>
            </div>
          </div>

          <div className="sc-controls">
            {stage === 'edit' ? (
              <>
                <div className="seg seg--fill" role="group" aria-label={t('share.card_title')} style={{ marginBottom: 14 }}>
                  <button type="button" aria-pressed={format === 'story'} onClick={() => setFormat('story')}>{t('share.card_story')}</button>
                  <button type="button" aria-pressed={format === 'post'} onClick={() => setFormat('post')}>{t('share.card_post')}</button>
                </div>
                <div className="t-label" style={{ marginBottom: 7 }}>{t('share.card_bg')}</div>
                {/* Only the Standard background for now; more styles land here later. */}
                <div style={{ marginBottom: 16 }}>
                  <div style={{ position: 'relative', width: 72, height: 72, borderRadius: 13, overflow: 'hidden', border: '2.5px solid var(--brand)', boxShadow: '0 0 0 3px var(--brand-soft)', background: 'var(--primary-soft)' }}>
                    <span className="t-nano" style={{ position: 'absolute', left: 0, right: 0, bottom: 0, background: 'rgba(20,25,35,.55)', color: '#fff', textAlign: 'center', padding: '2px 0' }}>{t('share.card_bg_standard')}</span>
                  </div>
                </div>
                <Btn className="sc-build" variant="primary" icon="map" loading={cardLoading} onClick={buildCard}>{t('share.card_build')}</Btn>
              </>
            ) : (
              <div className="sc-actions">
                <Btn className="sc-share" variant="primary" icon="share" onClick={shareCard} disabled={!cardUrl}>{t('share.card_share')}</Btn>
                <div className="sc-actions-sec">
                  <Btn variant="ghost" icon="edit" onClick={() => setStage('edit')}>{t('share.card_back')}</Btn>
                  <Btn variant="ghost" icon="download" onClick={downloadCard} disabled={!cardUrl}>{t('share.card_download')}</Btn>
                </div>
              </div>
            )}

            {cardErrorMsg && (
              <div style={{ marginTop: 12 }}>
                <Severity level="error">{cardErrorMsg}</Severity>
              </div>
            )}
          </div>
        </div>
      </div>
    </Dialog>
  );
}
