-- TRIP-236 (part 2) — enrich non-RU cities with tripster_slug / tripster_id.
--
-- Backfills the non-RU part of the Tripster feed (~665 cities) onto the cities
-- affiliate directory. Most already exist (Viator/GetYourGuide) -> UPDATE by
-- geonameid; Tripster-only cities -> INSERT (cities.id is GENERATED ALWAYS AS
-- IDENTITY, so id is never supplied).
--
-- Resolution at apply time against geo_gazetteer (dev & prod load the SAME
-- GeoNames data -> deterministic). To dodge the "exonym trap" (Tripster `en` is
-- often the native name, e.g. Milano/Venezia, exact-matching a DIFFERENT small
-- town's asciiname), each city is resolved by THREE independent signals -- ru-name
-- (FTS), en-name (FTS), exact asciiname -- population-first, and APPLIED only when
-- at least 2 of the 3 agree on the same geonameid. Ambiguous / single-signal
-- cities (Venice, New York, region/island proxies) are left unenriched on purpose
-- rather than risk a wrong affiliate link. Deduped by geonameid (population-first).
--
-- caps-guard: allow-uncapped -- _tf/_gz are transient staging temp tables (ON
-- COMMIT DROP), not persisted user columns; cities.tripster_* are capped.

CREATE TEMP TABLE _tf (ru text, en text, iata text, slug text, cc text, tid text) ON COMMIT DROP;
INSERT INTO _tf (ru, en, iata, slug, cc, tid) VALUES
('Тбилиси','Tbilisi','TBS','Tbilisi','GE','60'),
('Стамбул','Istanbul','IST','Istanbul','TR','18'),
('Ереван','Yerevan','EVN','Yerevan','AM','220'),
('Минск','Minsk','MSQ','Minsk','BY','287'),
('Рим','Rome','ROM','Rome','IT','4'),
('Париж','Paris','PAR','Paris','FR','3'),
('Баку','Baku','BAK','Baku','AZ','384'),
('Анталья','Antalya','AYT','Antalya','TR','83'),
('Пекин','Beijing','BJS','Beijing','CN','110'),
('Самарканд','Samarqand','SKD','Samarqand','UZ','390'),
('Батуми','Batumi','BUS','Batumi','GE','292'),
('Флоренция','Florence','FLR','Florence','IT','54'),
('Шарм-эль-Шейх','Sharm El Sheikh','SSH','Sharm_El_Sheikh','EG','770'),
('Лиссабон','Lisbon','LIS','Lisbon','PT','34'),
('Прага','Prague','PRG','Prague','CZ','7'),
('Бали','Denpasar','DPS','Bali','ID','103'),
('Гагра','Gagra',NULL,'Gagra','GE','657'),
('Будапешт','Budapest','BUD','Budapest','HU','19'),
('Милан','Milano','MIL','Milan','IT','93'),
('Белград','Belgrade','BEG','Belgrade','RS','148'),
('Каппадокия','Cappadocia',NULL,'Cappadocia','TR','455'),
('Дели','Delhi','DEL','Delhi','IN','389'),
('Шанхай','Shanghai','SHA','Shanghai','CN','45'),
('Нячанг','Nha Trang','NHA','Nha_Trang','VN','296'),
('Белек','Belek',NULL,'Belek','TR','612'),
('Мадрид','Madrid','MAD','Madrid','ES','46'),
('Сухум','Sokhumi','SUI','Sokhumi','GE','413'),
('Гродно','Hrodna','GNA','Grodno','BY','494'),
('Неаполь','Naples','NAP','Naples','IT','134'),
('Кейптаун','Cape Town','CPT','Cape_Town','ZA','247'),
('Будва','Budva','TIV','Budva','ME','80'),
('Мюнхен','Munich','MUC','Munich','DE','21'),
('Куала-Лумпур','Kuala Lumpur','KUL','Kuala_Lumpur','MY','261'),
('Коломбо','Colombo','CMB','Colombo','LK','488'),
('Касабланка','Casablanca','CAS','Casablanca','MA','85'),
('Киото','Kyoto','UKY','Kyoto','JP','480'),
('Занзибар','Zanzibar','ZNZ','Zanzibar','TZ','726'),
('Порту','Porto','OPO','Porto','PT','120'),
('Пицунда','Pitsunda',NULL,'Pitsunda','GE','600'),
('Верона','Verona','VRN','Verona','IT','84'),
('Рио-де-Жанейро','Rio de Janeiro','RIO','Rio_de_Janeiro','BR','117'),
('Ницца','Nice','NCE','Nice','FR','212'),
('Фетхие','Fethiye','DLM','Fethiye','TR','495'),
('Стокгольм','Stockholm','STO','Stockholm','SE','49'),
('Витебск','Vitebsk','VTB','Vitebsk','BY','65'),
('Шарджа','Sharjah','SHJ','Sharjah','AE','472'),
('Мармарис','Marmaris','QRQ','Marmaris','TR','587'),
('Генуя','Genoa','GOA','Genoa','IT','226'),
('Гоа','Goa','GOI','Goa','IN','388'),
('Осака','Osaka','OSA','Osaka','JP','999'),
('Чэнду','Chengdu','CTU','Chengdu','CN','951'),
('Копенгаген','Copenhagen','CPH','Copenhagen','DK','86'),
('Катманду','Kathmandu','KTM','Kathmandu','NP','87'),
('Фуджейра','Fujairah','FJR','Fujairah','AE','953'),
('Сиань','Sian','XIY','Sian','CN','899'),
('Марсель','Marseille','MRS','Marseille','FR','324'),
('Аджман','Ajman','QAJ','Ajman','AE','573'),
('Улан-Батор','Ulan-Bator','ULN','Ulan_Bator','MN','886'),
('София','Sofia','SOF','Sofia','BG','58'),
('Мцхета','Mtskheta',NULL,'Mtskheta','GE','221'),
('Майами','Miami','MIA','Miami','US','468'),
('Краков','Krakow','KRK','Krakow','PL','289'),
('Чунцин','Chongqing',NULL,'Chongqing','CN','1070'),
('Палермо','Palermo','PMO','Palermo','IT','167'),
('Сараево','Saraevo','SJJ','Saraevo','BA','968'),
('Кёльн','Koeln','CGN','Cologne','DE','62'),
('Гамбург','Hamburg','HAM','Hamburg','DE','143'),
('Ираклион','Heraklion',NULL,'Heraklion','GR','511'),
('Маэ','Mahé','SEZ','Mahe','SC','685'),
('Турин','Turin','TRN','Turin','IT','169'),
('Несвиж','Nyasvizh',NULL,'Nyasvizh','BY','439'),
('Хиккадува','Hikkaduwa',NULL,'Hikkaduwa','LK','577'),
('Новый Афон','New Athos',NULL,'New_Athos','GE','842'),
('Канны','Cannes','CEQ','Cannes','FR','186'),
('Самуи','Samui','USM','Samui','TH','208'),
('Лос-Анджелес','Los Angeles','LAX','Los_Angeles','US','82'),
('Цюрих','Zurich','ZRH','Zurich','CH','209'),
('Зальцбург','Salzburg','SZG','Salzburg','AT','265'),
('Гавана','Havana','HAV','Havana','CU','394'),
('Страсбург','Strasbourg','SXB','Strasbourg','FR','217'),
('Корфу','Corfu','CFU','Corfu','GR','487'),
('Манила','Manila','MNL','Manila','PH','540'),
('Ханчжоу','Hangzhou','HGH','Hangzhou','CN','699'),
('Шэньчжэнь','Shenzhen','SZX','Shenzhen','CN','1207'),
('Мехико','Mexico City','MEX','Mexico','MX','437'),
('Краби','Krabi',NULL,'Krabi','TH','507'),
('Антверпен','Antwerpen','ANR','Antwerpen','BE','31'),
('Женева','Geneve','GVA','Geneva','CH','101'),
('Пиза','Pisa','PSA','Pisa','IT','227'),
('Эдинбург','Edinburgh','EDI','Edinburgh','GB','124'),
('Вроцлав','Wroclaw','WRO','Wroclaw','PL','429'),
('Александрия','Alexandria','ALY','Alexandria','EG','807'),
('Ош','Osh','OSS','Osh','KG','837'),
('Люксембург','Luxembourg','LUX','Luxembourg','LU','66'),
('Варшава','Warsaw','WAW','Warsaw','PL','112'),
('Дрезден','Dresden','DRS','Dresden','DE','228'),
('Ларнака','Larnaca','LCA','Larnaca','CY','430'),
('Понта-Делгада','Ponta Delgada',NULL,'Ponta_Delgada','PT','715'),
('Каш','Kas',NULL,'Kas','TR','864'),
('Чикаго','Chicago','CHI','Chicago','US','159'),
('Мумбаи','Mumbai','BOM','Mumbai','IN','423'),
('Дахаб','Dahab',NULL,'Dahab','EG','796'),
('Гранада','Granada','GRX','Granada','ES','35'),
('Амальфи','Amalfi',NULL,'Amalfi','IT','196'),
('Бургас','Burgas','BOJ','Burgas','BG','282'),
('Айя-Напа','Ayia Napa',NULL,'Ayia_Napa','CY','344'),
('Протарас','Protaras',NULL,'Protaras','CY','635'),
('Брюгге','Brugge',NULL,'Brugge','BE','33'),
('Бар','Bar',NULL,'Bar','ME','67'),
('Жирона','Girona','GRO','Girona','ES','234'),
('Тирана','Tirana','TIA','Tirana','AL','319'),
('Камакура','Kamakura',NULL,'Kamakura','JP','351'),
('Варадеро','Varadero','VRA','Varadero','CU','434'),
('Лас-Вегас','Las Vegas','LAS','Las_Vegas','US','516'),
('Марса-Алам','Marsa Alam','RMF','Marsa_Alam','EG','828'),
('Могилёв','Mogilev','MVQ','Mogilev','BY','849'),
('Куньмин','Kunming','KMG','Kunming','CN','965'),
('Ашхабад','Ashgabat','ASB','Ashgabat','TM','1111'),
('Пусан','Busan','PUS','Busan','KR','1206'),
('Йокогама','Yokohama-shi','YOK','Yokohama','JP','123'),
('Бергамо','Bergamo','BGY','Bergamo','IT','215'),
('Катания','Catania','CTA','Catania','IT','285'),
('Петра','Petra',NULL,'Petra','JO','330'),
('Брешиа','Brescia','BRZ','Brescia','IT','368'),
('Кито','Quito','UIO','Quito','EC','418'),
('Люцерн','Lucerne',NULL,'Lucerne','CH','574'),
('Монреаль','Montreal','YMQ','Montreal','CA','603'),
('Монпелье','Montpellier','MPL','Montpellier','FR','630'),
('Фес','Fes','FEZ','Fes','MA','728'),
('Ванадзор','Vanadzor',NULL,'Vanadzor','AM','870'),
('Демре','Demre',NULL,'Demre','TR','1001'),
('Нара','Nara',NULL,'Nara','JP','1012'),
('Валлетта','Valletta','MLA','Valletta','MT','29'),
('Бремен','Bremen','BRE','Bremen','DE','128'),
('Толедо','Toledo',NULL,'Toledo','ES','163'),
('Руан','Rouen','URO','Rouen','FR','180'),
('Кишинёв','Chisinau','KIV','Chisinau','MD','246'),
('Лозанна','Lausanne',NULL,'Lausanne','CH','322'),
('Сан-Себастьян','San Sebastian','EAS','San_Sebastian','ES','334'),
('Гомель','Gomel','GME','Gomel','BY','513'),
('Ретимно','Rethymno','ZRE','Rethymno','GR','535'),
('Орвието','Orvieto',NULL,'Orvieto','IT','620'),
('Монтевидео','Montevideo','MVD','Montevideo','UY','750'),
('Тулум','Tulum',NULL,'Tulum','MX','803'),
('Рабат','Rabat','RBA','Rabat','MA','860'),
('Варанаси','Varanasi','VNS','Varanasi','IN','884'),
('Джидда','Jeddah','JED','Jeddah','SA','927'),
('Невшехир','Nevsehir',NULL,'Nevsehir','TR','1002'),
('Сафага','Safaga',NULL,'Safaga','EG','1027'),
('Хиросима','Hiroshima','HIJ','Hiroshima','JP','1196'),
('Хайкоу','Haikou','HAK','Haikou','CN','1222'),
('Скопье','Skopje','SKP','Skopje','MK','78'),
('Эйлат','Eilat',NULL,'Eilat','IL','183'),
('Хаммамет','Hammamet','NBE','Hammamet','TN','259'),
('Биарриц','Biarritz','BIQ','Biarritz','FR','360'),
('Лагуш','Lagos',NULL,'Lagos','PT','456'),
('Альба','Alba',NULL,'Alba','IT','466'),
('Вальпараисо','Valparaiso','VAP','Valparaiso','CL','557'),
('Байё','Bayeux',NULL,'Bayeux','FR','598'),
('Миконос','Mykonos','JMK','Mykonos','GR','652'),
('Помпеи','Pompei',NULL,'Pompei','IT','721'),
('Велигама','Weligama',NULL,'Weligama','LK','808'),
('Асуан','Asuan','ASW','Asuan','EG','854'),
('Виндхук','Windhoek','WDH','Windhoek','NA','892'),
('Макао','Macau','MFM','Macau','MO','896'),
('Инчхон','Incheon','ICN','Incheon','KR','910'),
('Луангпрабанг','Luangprabang','LPQ','Luangprabang','LA','926'),
('Чеджу','Jeju','CJU','Jeju','KR','975'),
('Ушуайя','Ushuaia','USH','Ushuaia','AR','1010'),
('Браслав','Braslav',NULL,'Braslav','BY','1134'),
('Каракол','Karakol',NULL,'Karakol','KG','1167'),
('Хайфа','Haifa','HFA','Haifa','IL','64'),
('Инсбрук','Innsbruck','INN','Innsbruck','AT','150'),
('Порто-Черво','Porto Cervo',NULL,'Porto_Cervo','IT','214'),
('Кембридж','Cambridge','CBG','Cambridge','GB','262'),
('Сиракузы','Syracuse',NULL,'Syracuse','IT','281'),
('Реймс','Reims','RHE','Reims','FR','340'),
('Альберобелло','Alberobello',NULL,'Alberobello','IT','373'),
('Сан-Ремо','San Remo',NULL,'San_Remo','IT','436'),
('Мурсия','Murcia',NULL,'Murcia','ES','560'),
('Квебек','Quebec','YQB','Quebec','CA','593'),
('Вьентьян','Vientiane','VTE','Vientiane','LA','594'),
('Ханья','Chania',NULL,'Chania','GR','605'),
('Авиньон','Avignon',NULL,'Avignon','FR','625'),
('Матера','Matera',NULL,'Matera','IT','650'),
('Кочин','Cochin','COK','Cochin','IN','731'),
('Бохол','Bohol',NULL,'Bohol','PH','736'),
('Панама','Panama','PTY','Panama','PA','820'),
('Кушадасы','Kusadasi',NULL,'Kusadasi','TR','829'),
('Лангкави','Langkawi','LGK','Langkawi','MY','908'),
('Лабуханбаджо','Labuhanbajo',NULL,'Labuhanbajo','ID','950'),
('Мантуя','Mantua',NULL,'Mantua','IT','990'),
('Диярбакыр','Diyarbakir','DIY','Diyarbakir','TR','1021'),
('Фос-ду-Игуасу','Foz do Iguacu','IGU','Foz_do_Iguacu','BR','1108'),
('Кавагоэ','Kawagoe',NULL,'Kawagoe','JP','1119'),
('Танжер','Tangier','TNG','Tangier','MA','1174'),
('Саппоро','Sapporo',NULL,'Sapporo','JP','1177'),
('Нукус','Nukus','NCU','Nukus','UZ','1212'),
('Ванкувер','Vancouver','YVR','Vancouver','CA','125'),
('Анси','Annecy','NCY','Annecy','FR','271'),
('Остуни','Ostuni',NULL,'Ostuni','IT','303'),
('Любек','Lubeck',NULL,'Lubeck','DE','345'),
('Больцано','Bolzano','BZO','Bolzano','IT','362'),
('Базель','Basel','BSL','Basel','CH','424'),
('Орлеан','Orléans','ORE','Orleans','FR','458'),
('Акаба','Aqaba','AQJ','Aqaba','JO','467'),
('Капри','Capri','PRJ','Capri','IT','509'),
('Бамберг','Bamberg',NULL,'Bamberg','DE','542'),
('Солнечный Берег','Sunny Beach',NULL,'Sunny_Beach','BG','629'),
('Фару','Faro','FAO','Faro','PT','642'),
('Портофино','Portofino',NULL,'Portofino','IT','649'),
('Окленд','Auckland','AKL','Auckland','NZ','687'),
('Пинск','Pinsk',NULL,'Pinsk','BY','875'),
('Ченнаи','Chennai','MAA','Chennai','IN','881'),
('Сванетия','Svanetia',NULL,'Svanetia','GE','911'),
('Тайбэй','Taipei','TPE','Taipei','TW','915'),
('Ленкорань','Lenkoran','LLK','Lenkoran','AZ','945'),
('Эперне','Epernay','XEP','Epernay','FR','954'),
('Пуэрто-Монт','Puerto Montt','PMC','Puerto_Montt','CL','977'),
('Сумгаит','Sumgayit',NULL,'Sumgayit','AZ','996'),
('Хайдельберг','Heidelberg',NULL,'Heidelberg','DE','1074'),
('Заславль','Zaslawye',NULL,'Zaslawye','BY','1141'),
('Миоры','Miory',NULL,'Miory','BY','1170'),
('Боракай','Boracay','MPH','Boracay','PH','1180'),
('Джермук','Jermuk',NULL,'Dzhermuk','AM','1223'),
('Гауда','Gouda',NULL,'Gouda','NL','94'),
('Брно','Brno','BRQ','Brno','CZ','130'),
('Лонгйир','Longyearbyen','LYR','Longyearbyen','SJ','210'),
('Аугсбург','Augsburg',NULL,'Augsburg','DE','233'),
('Ульм','Ulm',NULL,'Ulm','DE','238'),
('Монополи','Monopoli',NULL,'Monopoli','IT','304'),
('Дуррес','Durrës',NULL,'Durres','AL','313'),
('Аахен','Aachen','AAH','Aachen','DE','325'),
('Мальмё','Malmo','MMA','Malmo','SE','343'),
('Лилль','Lille','LIL','Lille','FR','355'),
('Неймеген','Nijmegen',NULL,'Nijmegen','NL','358'),
('Ново-Место','Novo Mesto',NULL,'Novo_Mesto','SI','378'),
('Ним','Nimes','FNI','Nimes','FR','448'),
('Канди','Kandy','KDW','Kandy','LK','469'),
('Крит','Crete','HER','Crete','GR','484'),
('Корсика','Corsica','AJA','Corsica','FR','514'),
('Сорренто','Sorrento','RRO','Sorrento','IT','521'),
('Гибралтар','Gibraltar','GIB','Gibraltar','GI','524'),
('Янгон','Yangon','RGN','Yangon','MM','576'),
('Тарту','Tartu',NULL,'Tartu','EE','583'),
('Стреза','Streza',NULL,'Stresa','IT','627'),
('Пловдив','Plovdiv',NULL,'Plovdiv','BG','644'),
('Комо','Como',NULL,'Como','IT','660'),
('Версаль','Versailles',NULL,'Versailles','FR','673'),
('Оттава','Ottawa','YOW','Ottawa','CA','684'),
('Манчестер','Manchester','MAN','Manchester','GB','691'),
('Синая','Sinaia',NULL,'Sinaia','RO','705'),
('Рупит','Rupit',NULL,'Rupit','ES','722'),
('Позитано','Positano',NULL,'Positano','IT','734'),
('Бразилиа','Brasilia','BSB','Brasilia','BR','740'),
('Катерини','Katerini',NULL,'Katerini','GR','797'),
('Пиран','Piran',NULL,'Piran','SI','825'),
('Бангалор','Bangalor','BLR','Bangalor','IN','872'),
('Висмар','Wismar','DE','Wismar','DE','901'),
('Монблан','Montblanc',NULL,'Montblanc','ES','912'),
('Сремски-Карловци','Sremski Karlovci',NULL,'Sremski_Karlovci','RS','920'),
('Мдина','Mdina',NULL,'Mdina','MT','928'),
('Шемаха','Shamakhi',NULL,'Shamakhi','AZ','940'),
('Сарагоса','Zaragoza','ZAZ','Zaragoza','ES','946'),
('Дордрехт','Dordrecht',NULL,'Dordrecht','NL','963'),
('Хорн','Hoorn',NULL,'Hoorn','NL','969'),
('Катовице','Katowice','KTW','Katowice','PL','985'),
('Виченца','Vicenza','VIC','Vicenza','IT','993'),
('Кортона','Cortona',NULL,'Cortona','IT','1020'),
('Хуньчунь','Hunchun',NULL,'Hunchun','CN','1023'),
('Тривандрум','Trivandrum','TRV','Trivandrum','IN','1030'),
('Тюбинген','Tubingen',NULL,'Tubingen','DE','1071'),
('Удине','Udine','UDN','Udine','IT','1109'),
('Боббио','Bobbio',NULL,'Bobbio','IT','1112'),
('Нафплион','Nafplion',NULL,'Nafplion','GR','1117'),
('Пьяченца','Piacenza','QPZ','Piacenza','IT','1121'),
('Сигишоара','Sighisoara',NULL,'Sighisoara','RO','1124'),
('Хойан','Hoi An','KHY','Hoi_An','VN','1132'),
('Кумамото','Kumamoto','KMJ','Kumamoto','JP','1133'),
('Слуцк','Slutsk',NULL,'Slutsk','BY','1142'),
('Новолукомль','Novolukoml',NULL,'Novolukoml','BY','1144'),
('Ла Специя','La Spezia',NULL,'La_Spezia','IT','1148'),
('Иджеван','Ijevan',NULL,'Ijevan','AM','1150'),
('Пуэрто-Игуасу','Puerto Iguazu','IGR','Puerto_Iguasu','AR','1171'),
('Дауин','Dauin',NULL,'Dauin','PH','1184'),
('Каламбака','Kalambaka',NULL,'Kalambaka','GR','1189'),
('Удзи','Uji',NULL,'Uji','JP','1198'),
('Лахор','Lahore','LHE','Lahore','PK','1200'),
('Цхинвал','Tskhinvali',NULL,'Tskhinvali','GE','1213'),
('Хьюстон','Houston','IAH','Houston','US','1215'),
('Денвер','Denver','DEN','Denver','US','1218'),
('Познань','Poznan','POZ','Poznan','PL','1262'),
('Шарлеруа','Charleroi','CRL','Charleroi','BE','1264'),
('Закинтос','Zakynthos','ZTH','Zakynthos','GR','1267'),
('Анхелес','Angeles City','CRK','Angeles','PH','1269'),
('Дубай','Dubai','DXB','Dubai','AE','92'),
('Барселона','Barcelona','BCN','Barcelona','ES','6'),
('Ташкент','Tashkent','TAS','Tashkent','UZ','61'),
('Пхукет','Phuket','HKT','Phuket','TH','299'),
('Каир','Cairo','CAI','Cairo','EG','727'),
('Куэнка','Cuenca','CUE','Cuenca','EC','1275'),
('Урумчи','Urumqi','URC','Urumqi','CN','1281'),
('Парати','Paraty','JPY','Paraty','BR','1283'),
('Амбуаз','Amboise',NULL,'Amboise','FR','1286'),
('Фучжоу','Fuzhou','FOC','Fuzhou','CN','1290'),
('Орша','Orsha',NULL,'Orsha','BY','1296'),
('Момбаса','Mombasa','MBA','Mombasa','KE','1299'),
('Бове','Beauvais','BV','Beauvais','FR','1301'),
('Кагосима','Kagoshima','KOJ','Kagoshima','JP','1303'),
('Алжир','Algiers','ALG','Alzhir','DZ','1337'),
('Мисима','Mishima',NULL,'Mishima','JP','1339'),
('Токио','Tokyo','TYO','Tokyo','JP','57'),
('Кемер','Kemer',NULL,'Kemer','TR','454'),
('Алматы','Almaty','ALA','Almaty','KZ','474'),
('Хургада','Hurghada','HRG','Hurghada','EG','253'),
('Аланья','Alanya','GZP','Alanya','TR','201'),
('Венеция','Venezia','VCE','Venice','IT','24'),
('Сиде','Side',NULL,'Side','TR','453'),
('Бишкек','Bishkek','FRU','Bishkek','KG','669'),
('Лондон','London','LON','London','GB','16'),
('Амстердам','Amsterdam','AMS','Amsterdam','NL','22'),
('Бангкок','Bangkok','BKK','Bangkok','TH','99'),
('Маскат','Muscat','MCT','Muscat','OM','243'),
('Паттайя','Phatthaya','PYX','Pattaya','TH','68'),
('Брест','Brest','BQT','Brest','BY','376'),
('Вена','Vienna','VIE','Vienna','AT','5'),
('Бухара','Buxoro','BHK','Bukhara','UZ','74'),
('Сеул','Seoul','SEL','Seoul','KR','403'),
('Абу-Даби','Abu Dhabi','AUH','Abu_Dhabi','AE','470'),
('Доха','Doha','DOH','Doha','QA','858'),
('Кутаиси','Kutaisi','KUT','Kutaisi','GE','357'),
('Берлин','Berlin','BER','Berlin','DE','23'),
('Буэнос-Айрес','Buenos Aires','BAI','Buenos_Aires','AR','204'),
('Астана','Astana','TSE','Astana','KZ','364'),
('Рига','Riga','RIX','Riga','LV','8'),
('Санья','Sanya','SYX','Sanya','CN','882'),
('Таллин','Tallinn','TLL','Tallinn','EE','26'),
('Хошимин','Ho Chi Minh City','SGN','Ho_Chi_Minh','VN','43'),
('Тенерифе','Santa Cruz de Tenerife','TCI','Tenerife','ES','135'),
('Нью-Йорк','New York','NYC','New_York','US','44'),
('Афины','Athens','ATH','Athens','GR','164'),
('Гуанчжоу','Guangzhou','CAN','Guangzhou','CN','56'),
('Хива','Khiva',NULL,'Khiva','UZ','683'),
('Валенсия','Valencia','VLC','Valencia','ES','114'),
('Иерусалим','Jerusalem','JRS','Jerusalem','IL','53'),
('Бодрум','Bodrum','BXN','Bodrum','TR','628'),
('Вильнюс','Vilnius','VNO','Vilnius','LT','25'),
('Рас-эль-Хайма','Ras Al Khaimah','RKT','Ras_Al_Khaimah','AE','676'),
('Дананг','Danang','DAD','Danang','VN','708'),
('Болонья','Bologna','BLQ','Bologna','IT','263'),
('Порт-Луи','Port_Louis','MRU','Port_Louis','MU','270'),
('Гюмри','Gyumri','LWN','Gyumri','AM','680'),
('Родос','Rhodes','RHO','Rhodes','GR','375'),
('Душанбе','Dushanbe','DYU','Dushanbe','TJ','857'),
('Мадейра','Madeira','FNC','Madeira','PT','166'),
('Сингапур','Singapore','SIN','Singapore','SG','250'),
('Ханой','Hanoi','HAN','Hanoi','VN','534'),
('Тель-Авив','Tel Aviv','TLV','Tel_Aviv','IL','42'),
('Убуд','Ubud',NULL,'Ubud','ID','894'),
('Актау','Aktau','SCO','Aktau','KZ','906'),
('Севилья','Sevilla','SVQ','Sevilla','ES','383'),
('Лимассол','Limassol',NULL,'Limassol','CY','206'),
('Манама','Manama','BAH','Manama','BH','710'),
('Брюссель','Brussels','BRU','Brussels','BE','27'),
('Малага','Malaga','AGP','Malaga','ES','122'),
('Луксор','Luxor','LXR','Luxor','EG','802'),
('Лион','Lyon','LYS','Lyon','FR','255'),
('Рейкьявик','Reykjavik','REK','Reykjavik','IS','30'),
('Сиемреап','Siemreap','REP','Siemreap','KH','258'),
('Дубровник','Dubrovnik','DBV','Dubrovnik','HR','385'),
('Тиват','Tivat',NULL,'Tivat','ME','431'),
('Фантьет','Phan Thiet',NULL,'Phan_Thiet','VN','461'),
('Хельсинки','Helsinki','HEL','Helsinki','FI','15'),
('Мале','Male','MLE','Male','MV','141'),
('Себу','Cebu',NULL,'Cebu','PH','447'),
('Камрань','Cam Ranh','CXR','Cam_Ranh','VN','983'),
('Бордо','Bordeaux','BOD','Bordeaux','FR','170'),
('Марракеш','Marrakesh','RAK','Marrakesh','MA','438'),
('Аликанте','Alicante','ALC','Alicante','ES','81'),
('Нови-Сад','Novi Sad','QND','Novi_Sad','RS','426'),
('Галле','Galle',NULL,'Galle','LK','809'),
('Сидней','Sydney','SYD','Sydney','AU','59'),
('Салоники','Thessaloniki','SKG','Thessaloniki','GR','136'),
('Котор','Kotor',NULL,'Kotor','ME','264'),
('Гран-Канария','Gran Canaria','ACE','Gran_Canaria','ES','374'),
('Полоцк','Polatsk',NULL,'Polotsk','BY','140'),
('Канкун','Cancun','CUN','Cancun','MX','207'),
('Братислава','Bratislava','BTS','Bratislava','SK','260'),
('Фукуок','Phu Quoc',NULL,'Phu_Quoc','VN','527'),
('Као Лак','Khao Lak',NULL,'Khao_Lak','TH','586'),
('Кобулети','Kobuleti',NULL,'Kobuleti','GE','533'),
('Монако','Monaco',NULL,'Monaco','MC','590'),
('Чолпон-Ата','Cholpon-Ata',NULL,'Cholpon_Ata','KG','839'),
('Гудаута','Gudauta',NULL,'Gudauta','GE','1166'),
('Бари','Bari','BRI','Bari','IT','175'),
('Пафос','Paphos',NULL,'Paphos','CY','483'),
('Херцег-Нови','Herceg Novi','HNO','Herceg_Novi','ME','671'),
('Дилижан','Dilijan',NULL,'Dilijan','AM','867'),
('Осло','Oslo','OSL','Oslo','NO','32'),
('Сан-Франциско','San Francisco','SFO','San_Francisco','US','55'),
('Мельбурн','Melbourne','MEL','Melbourne','AU','111'),
('Дюссельдорф','Duesseldorf','DUS','Duesseldorf','DE','241'),
('Чжанцзяцзе','Zhangjiajie',NULL,'Zhangjiajie','CN','925'),
('Пальма-де-Майорка','Palma de Mallorca','PMI','Palma_de_Mallorca','ES','367'),
('Амман','Amman','AMM','Amman','JO','823'),
('Чиангмай','Chiang Mai','CNX','Chiang_Mai','TH','73'),
('Синтра','Sintra',NULL,'Sintra','PT','127'),
('Богота','Bogota','BOG','Bogota','CO','129'),
('Бильбао','Bilbao','BIO','Bilbao','ES','359'),
('Сплит','Split','SPU','Split','HR','492'),
('Бухарест','Bucharest','OTP','Bucharest','RO','505'),
('Джайпур','Jaipur','JAI','Jaipur','IN','869'),
('Шымкент','Shymkent','CIT','Shymkent','KZ','981'),
('Эль-Аламейн','El Alamein','DBB','El_Alamein','EG','1158'),
('Окинава','Okinawa','OKA','Okinawa','JP','326'),
('Фукуока','Fukuoka',NULL,'Fukuoka','JP','1123'),
('Торонто','Toronto','YTO','Toronto','CA','52'),
('Ольбия','Olbia','OLB','Olbia','IT','211'),
('Таррагона','Tarragona',NULL,'Tarragona','ES','307'),
('Лукка','Lucca','LCV','Lucca','IT','427'),
('Муйне','Muine','PHH','Muine','VN','496'),
('Сантьяго','Santiago','SCL','Santiago','CL','943'),
('Бенидорм','Benidorm',NULL,'Benidorm','ES','980'),
('Дублин','Dublin','DUB','Dublin','IE','75'),
('Нюрнберг','Nuernberg','NUE','Nuremberg','DE','95'),
('Кольмар','Colmar','CMR','Colmar','FR','256'),
('Варна','Varna','VAR','Varna','BG','331'),
('Измир','Izmir','ADB','Izmir','TR','723'),
('Калгари','Calgary','YYC','Calgary','CA','939'),
('Лида','Lida',NULL,'Lida','BY','949'),
('Ургенч','Urgench','UGC','Urganch','UZ','1017'),
('Финике','Finike',NULL,'Finike','TR','1154'),
('Боровое','Borovoye',NULL,'Borovoye','KZ','1168'),
('Харбин','Harbin','HRB','Harbin','CN','1220'),
('Акко','Akko',NULL,'Acre','IL','98'),
('Брашов','Brasov',NULL,'Brasov','RO','189'),
('Блед','Bled',NULL,'Bled','SI','202'),
('Михас','Mijas',NULL,'Mihas','ES','1208'),
('Тронхейм','Trondheim',NULL,'Tronheim','NO','1209'),
('Термез','Termez','TMJ','Termez','UZ','1214'),
('Аштарак','Ashtarak',NULL,'Ashtarak','AM','1216'),
('Роттердам','Rotterdam','RTM','Rotterdam','NL','473'),
('Лоян','Luoyang','LYA','Luoyang','CN','479'),
('Загреб','Zagreb','ZAG','Zagreb','HR','485'),
('Санторини','Santorini','JTR','Santorini','GR','498'),
('Бостон','Boston','BOS','Boston','US','517'),
('Баден-Баден','Baden-Baden','ZCC','Baden-Baden','DE','545'),
('Даламан','Dalaman',NULL,'Dalaman','TR','887'),
('Сан-Паулу','Sao Paulo','SAO','Sao_Paulo','BR','961'),
('Гуйлинь','Guilin','KWL','Guilin','CN','1018'),
('Салала','Salalah','SLL','Salala','OM','1135'),
('Перуджа','Perugia','PEG','Perugia','IT','76'),
('Гаага','The Hague',NULL,'The_Hague','NL','198'),
('Тунис','Tunis','TUN','Tunis','TN','254'),
('Кордова','Córdoba','ODB','Cordoba','ES','312'),
('Хаконе','Hakone',NULL,'Hakone','JP','350'),
('Грац','Graz','GRZ','Graz','AT','392'),
('Любляна','Ljubljana','LJU','Ljubljana','SI','399'),
('Падуя','Padova',NULL,'Padova','IT','531'),
('Тяньцзинь','Tianjin','TSN','Tianjin','CN','604'),
('Канадзава','Kanazawa',NULL,'Kanazawa','JP','653'),
('Агра','Agra','AGR','Agra','IN','868'),
('Олюдениз','Ölüdeniz',NULL,'Oludeniz','TR','871'),
('Нагоя','Nagoya','NKM','Nagoya','JP','1008'),
('Джокьякарта','Yogyakarta','YIA','Yogyakarta','ID','1072'),
('Оксфорд','Oxford','OXF','Oxford','GB','102'),
('Ганновер','Hannover','HAJ','Hannover','DE','132'),
('Гент','Gent',NULL,'Ghent','BE','174'),
('Лечче','Lecce','LCC','Lecce','IT','232'),
('Лхаса','Lhasa','LXA','Lhasa','CN','286'),
('Пунта-Кана','Punta Cana','PUJ','Punta_Cana','DO','288'),
('Равенна','Ravenna','RAN','Ravenna','IT','323'),
('Триест','Trieste','TRS','Trieste','IT','369'),
('Римини','Rimini','RMI','Rimini','IT','409'),
('Сиена','Siena','SAY','Siena','IT','537'),
('Таормина','Taormina',NULL,'Taormina','IT','546'),
('Гданьск','Gdansk',NULL,'Gdansk','PL','570'),
('Ситжес','Sitges',NULL,'Sitges','ES','348'),
('Торревьеха','Torrevieja',NULL,'Torrevieja','ES','370'),
('Лима','Lima','LIM','Lima','PE','462'),
('Утрехт','Utrecht','UTC','Utrecht','NL','463'),
('Потсдам','Potsdam',NULL,'Potsdam','DE','491'),
('Несебр','Nesebar',NULL,'Nesebar','BG','547'),
('Лейпциг','Leipzig',NULL,'Leipzig','DE','553'),
('Бентота','Bentota',NULL,'Bentota','LK','578'),
('Модена','Modena',NULL,'Modena','IT','606'),
('Ливорно','Livorno',NULL,'Livorno','IT','643'),
('Цандрипш','Tsandryphsh',NULL,'Tsandryphsh','GE','661'),
('Картахена','Cartagena',NULL,'Cartagena','ES','675'),
('Калутара','Kalutara',NULL,'Kalutara','LK','819'),
('Коканд','Kokand',NULL,'Kokand','UZ','835'),
('Кайсери','Kayseri','ASR','Kayseri','TR','890'),
('Сирмионе','Sirmione',NULL,'Sirmione','IT','909'),
('Харлем','Haarlem',NULL,'Haarlem','NL','914'),
('Никосия','Nicosia','NIC','Nikosia','CY','957'),
('Панглао','Panglao','TAG','Panglao','PH','992'),
('Мендоса','Mendoza','MDZ','Mendoza','AR','1011'),
('Джакарта','Jakarta','JKT','Jakarta','ID','1126'),
('Мерса-Матрух','Mersa Matruh','MUH','Mersa_Matruh','EG','1159'),
('Паро','Paro',NULL,'Paro','BT','1195'),
('Франкфурт','Frankfurt am Main','FRA','Frankfurt','DE','28'),
('Ассизи','Assisi',NULL,'Assisi','IT','77'),
('Делфт','Delft',NULL,'Delft','NL','126'),
('Салерно','Salerno','QSR','Salerno','IT','200'),
('Коимбра','Coimbra','CBP','Coimbra','PT','251'),
('Кальяри','Cagliari','CAG','Cagliari','IT','279'),
('Бейрут','Beirut','BEY','Beirut','LB','315'),
('Нагасаки','Nagasaki','NGS','Nagasaki','JP','328'),
('Риоха','La Rioja',NULL,'La_Rioja','ES','361'),
('Далат','Dalat','DLI','Dalat','VN','497'),
('Чианграй','Chiang Rai','CEI','Chiang_Rai','TH','532'),
('Агадир','Agadir','AGA','Agadir','MA','569'),
('Карловы Вары','Karlovy Vary',NULL,'Karlovy_Vary','CZ','579'),
('Ронда','Ronda','RRA','Ronda','ES','596'),
('Каунас','Kaunas','KUN','Kaunas','LT','597'),
('Сен-Мало','Saint-Malo',NULL,'Saint_Malo','FR','623'),
('Антиб','Antibes',NULL,'Antibes','FR','637'),
('Ментон','Menton',NULL,'Menton','FR','656'),
('Плайя-дель-Кармен','Playa del Carmen','PCM','Playa_del_Carmen','MX','697'),
('Пунта-дель-Эсте','Punta del Este','PDP','Punta_del_Este','UY','711'),
('Туркестан','Turkestan','HSA','Turkestan','KZ','934'),
('Эр-Рияд','Riyadh','RUH','Riyadh','SA','959'),
('Суботица','Subotica',NULL,'Subotica','RS','966'),
('Фергана','Ferghana','FEG','Ferghana','UZ','986'),
('Филадельфия','Philadelphia','PHL','Philadelphia','US','1009'),
('Питильяно','Pitigliano',NULL,'Pitigliano','IT','1113'),
('Беппу','Beppu','BPU','Beppu','JP','1164'),
('Палаван','Palawan','PPS','Palawan','PH','1176'),
('Парма','Parma','PMF','Parma','IT','1179'),
('Унаватуна','Unawatuna',NULL,'Unawatuna','LK','1202'),
('Мирисса','Mirissa',NULL,'Mirissa','LK','1203'),
('Турку','Turku','TKU','Turku','FI','37'),
('Лейден','Leiden',NULL,'Leiden','NL','121'),
('Байконур','Baikonur',NULL,'Baikonur','KZ','160'),
('Модика','Modica',NULL,'Modica','IT','294'),
('Регенсбург','Regensburg',NULL,'Regensburg','DE','305'),
('Мерано','Merano',NULL,'Merano','IT','347'),
('Витория-Гастейс','Vitoria-Gasteiz','VIT','Vitoria_Gasteiz','ES','371'),
('Вашингтон','Washington','WAS','Washington','US','402'),
('Бургос','Burgos','RGS','Burgos','ES','445'),
('Памплона','Pamplona','PNA','Pamplona','ES','446'),
('Аделаида','Adelaide','ADL','Adelaide','AU','460'),
('Нарва','Narva',NULL,'Narva','EE','486'),
('Чивитавеккья','Civitavecchia',NULL,'Civitavecchia','IT','538'),
('Чефалу','Cefalu',NULL,'Cefalu','IT','543'),
('Косумель','Cozumel','CZM','Cozumel','MX','568'),
('Гонолулу','Honolulu','HNL','Honolulu','US','622'),
('Кадис','Cadiz','CDZ','Cadiz','ES','648'),
('Бонн','Bonn',NULL,'Bonn','DE','668'),
('Джардини-Наксос','Giardini-Naxos',NULL,'Giardini_Naxos','IT','677'),
('Йоханнесбург','Johannesburg','JNB','Johannesburg','ZA','709'),
('Подгорица','Podgorica','TGD','Podgorica','ME','738'),
('Охрид','Ohrid','OHD','Ohrid','MK','818'),
('Пуэрто-Плата','Puerto Plata','POP','Puerto_Plata','DO','821'),
('Медельин','Medellin','EOH','Medellin','CO','826'),
('Кхаджурахо','Khajuraho','HJR','Khajuraho','IN','880'),
('Марбелья','Marbella','QRL','Marbella','ES','885'),
('Варкала','Varkala',NULL,'Varkala','IN','895'),
('Дхарамсала','Dharamsala','DHM','Dharamsala','IN','905'),
('Антананариву','Antananarivo','TNR','Antananarivo','MG','913'),
('Памуккале','Pamukkale','DNZ','Pamukkale','TR','917'),
('Бурса','Bursa','BTZ','Bursa','TR','938'),
('Кауаи','Kauai','LIH','Kauai','US','941'),
('Дезенцано-дель-Гарда','Desenzano del Garda',NULL,'Desenzano_del_Garda','IT','948'),
('Ванг Вьенг','Vang Vieng',NULL,'Vang_Vieng','LA','988'),
('Ареццо','Arezzo','QZO','Arezzo','IT','1000'),
('Арона','Arona',NULL,'Arona','IT','1032'),
('Сопот','Sopot',NULL,'Sopot','PL','1128'),
('Сус','Sousse','QSO','Sousse','TN','1160'),
('Боржоми','Borjomi',NULL,'Borjomi','GE','1173'),
('Брисбен','Brisbane','BNE','Brisbane','AU','1191'),
('Асунсьон','Asuncion','ASU','Asuncion','PY','1211'),
('Кеблавик','Keflavik','KEF','Keflavik','IS','1265'),
('Багио','Baguio','BAG','Baguio','PH','1276'),
('Сучжоу','Suzhou','SZV','Suchzhou','CN','1288'),
('Буйон','Bouillon',NULL,'Bouillon','BE','108'),
('Юрмала','Jurmala',NULL,'Jurmala','LV','116'),
('Эйндховен','Eindhoven','EIN','Eindhoven','NL','133'),
('Леднице','Lednice',NULL,'Lednice','CZ','168'),
('Лёвен','Leuven',NULL,'Leuven','BE','195'),
('Орхус','Aarhus','AAR','Aarhus','DK','219'),
('Анкара','Ankara','ANK','Ankara','TR','237'),
('Вильфранш-сюр-Сон','Villefranche-sur-Saône',NULL,'Villefranche-sur-Saone','FR','300'),
('Ливерпуль','Liverpool','LPL','Liverpool','GB','309'),
('Темпио Паусания','Tempio Pausania',NULL,'Tempio_Pausania','IT','332'),
('Киль','Kiel','KEL','Kiel','DE','346'),
('Отранто','Otranto',NULL,'Otranto','IT','354'),
('Альгеро','Alghero','AHO','Alghero','IT','356'),
('Наха','Naha-shi',NULL,'Naha_shi','JP','365'),
('Паланга','Palanga','PLQ','Palanga','LT','408'),
('Гренобль','Grenoble','GNB','Grenoble','FR','442'),
('Эс-Сувейра','Essaouira','ESU','Essaouira','MA','457'),
('Экс-ан-Прованс','Aix-en-Provence',NULL,'Aix_en_Provence','FR','477'),
('Найроби','Nairobi','NBO','Nairobi','KE','502'),
('Таити','Tahiti','PPT','Tahiti','PF','515'),
('Арль','Arles',NULL,'Arles','FR','548'),
('Сантьяго-де-Компостела','Santiago de Compostela','SCQ','Santiago_de_Compostela','ES','562'),
('Реус','Reus','REU','Reus','ES','613'),
('Лугано','Lugano','LUG','Lugano','CH','616'),
('Сан-Марино','San Marino','SM','San_Marino','SM','634'),
('Мадалена','Madalena',NULL,'Madalena','PT','654'),
('Изола','Izola',NULL,'Izola','SI','659'),
('Шикли','Scicli',NULL,'Scicli','IT','663'),
('Йорк','York',NULL,'York','GB','667'),
('Рагуза','Ragusa',NULL,'Ragusa','IT','682'),
('Грасс','Grasse',NULL,'Grasse','FR','703'),
('Назарет','Nazareth',NULL,'Nazareth','IL','713'),
('Фюссен','Fussen',NULL,'Fussen','DE','718'),
('Уранополис','Ouranoupoli',NULL,'Ouranoupoli','GR','729'),
('Обидуш','Obidos',NULL,'Obidos','PT','737'),
('Картахена','Cartagena','CTG','Cartagena_de_Indias','CO','861'),
('Даммам','Dammam',NULL,'Dammam','SA','863'),
('Шверин','Schwerin',NULL,'Schwerin','DE','907'),
('Фленсбург','Flensburg','FLF','Flensburg','DE','919'),
('Буффало','Buffalo','BUF','Buffalo','US','929'),
('Урбино','Urbino',NULL,'Urbino','IT','933'),
('Худжанд','Khujand','LBD','Khujand','TJ','935'),
('Анкона','Ancona','AOI','Ancona','IT','937'),
('Тулон','Tulon','TLN','Tulon','FR','942'),
('Порт-Блэр','Port Blair','IXZ','Port_Blair','IN','964'),
('Гётеборг','Gothenburg','GOT','Gothenburg','SE','984'),
('Пистоя','Pistoia',NULL,'Pistoia','IT','995'),
('Гянджа','Ganja','GNJ','Ganja','AZ','998'),
('Монтепульчано','Montepulciano',NULL,'Montepulciano','IT','1016'),
('Харлинген','Harlingen','HRL','Harlingen','NL','1026'),
('Полиньяно-а-Маре','Polignano a Mare',NULL,'Polignano_a_Mare','IT','1029'),
('Сан-Хосе','San Jose','SJO','San_Jose','CR','1107'),
('Аквилея','Aquileia',NULL,'Aquileia','IT','1110'),
('Гориция','Gorizia','QGO','Gorizia','IT','1116'),
('Сет','Set',NULL,'Set','FR','1120'),
('Нарвик','Narvik','NVK','Narvik','NO','1122'),
('Амасра','Amasra',NULL,'Amasra','TR','1127'),
('Колония-дель-Сакраменто','Colonia del Sacramento','CYR','Colonia_del_Sacramento','UY','1129'),
('Пелла','Pella',NULL,'Pella','GR','1136'),
('Новогрудок','Novogrudok',NULL,'Novogrudok','BY','1137'),
('Патры','Patras','GPA','Patry','GR','1139'),
('Вилейка','Vilyeyka',NULL,'Vilyeyka','BY','1143'),
('Шарковщина','Sharkovshchina',NULL,'Sharkovshchina','BY','1149'),
('Крань','Kranj',NULL,'Kranj','SI','1151'),
('Белфаст','Belfast','BFS','Belfast','GB','1156'),
('Эчмиадзин','Etchmiadzin',NULL,'Etchmiadzin','AM','1161'),
('Сидзуока','Shizuoka','FSZ','Shizuoka','JP','1172'),
('Сан-Себастьян-де-ла-Гомера','San Sebastian de La Gomera','GMZ','San_Sebastian_De_La_Gomera','ES','1181'),
('Усть-Каменогорск','Oskemen','UKK','Oskemen','KZ','1188'),
('Каяни','Kajaani','KAJ','Kajaani','FI','1192'),
('Констанц','Konstanz','QKZ','Konstanz','DE','1194'),
('Рюдесхайм','Rüdesheim am Rhein',NULL,'Rudesheim','DE','1199'),
('Феррара','Ferrara',NULL,'Ferrara','IT','1217'),
('Соронг','Sorong','SOQ','Sorong','ID','1221'),
('Манавгат','Manavgat',NULL,'Manavgat','TR','1225'),
('Ангра-ду-Эроишму','Angra do Heroismo','TER','Angra_do_Heroismo','PT','1226'),
('Аль-Айн','Al Ain','AAN','Al_Ain','AE','1261'),
('Кируна','Kiruna','KRN','Kiruna','SE','1263'),
('Ламеция','Lamezia','SUF','Lamezia','IT','1266'),
('Шамбери','Chambery','CMF','Chambery','FR','1268'),
('Мемминген','Memmingen','FMM','Memmingen','DE','1271'),
('Веце','Weeze','NRN','Vetse','DE','1272'),
('Кастельон-де-ла-Плана','Castello de la Plana','CDT','Castello_de_la_Plana','ES','1273'),
('Каркассон','Carcassonne','CCF','Carcasson','FR','1278'),
('Ухань','Wuhan','WUH','Uhan','CN','1291'),
('Форт-Лодердейл','Fort Lauderdale','FLL','Fort_Lauderdale','US','1298'),
('Пуэрто-Вальярта','Puerto Vallarta','PVR','Puerto_Vallarta','MX','1300'),
('Аруша','Arusha','ARK','Arusha','TZ','1302'),
('Кембридж','Cambridge',NULL,'Cambridge_US','US','1304'),
('Майнц','Mainz','QMZ','Mainz','DE','1338')
;

CREATE TEMP TABLE _gz ON COMMIT DROP AS
  SELECT country_code, geonameid, population,
         lower(regexp_replace(unaccent(asciiname),'[^a-z0-9]','','g')) AS nkey
  FROM public.geo_gazetteer
  WHERE country_code IN (SELECT DISTINCT cc FROM _tf);
CREATE INDEX ON _gz (country_code, nkey);

CREATE TEMP TABLE _res ON COMMIT DROP AS
WITH r AS (
  SELECT t.slug, t.tid, t.iata,
    (SELECT g.geonameid FROM public.geo_gazetteer g
       WHERE g.country_code=t.cc AND g.all_doc @@ plainto_tsquery('simple', translate(lower(t.ru),'ё','е'))
       ORDER BY g.population DESC NULLS LAST LIMIT 1) AS gid_ru,
    (SELECT g.geonameid FROM public.geo_gazetteer g
       WHERE g.country_code=t.cc AND g.all_doc @@ plainto_tsquery('simple', unaccent(t.en))
       ORDER BY g.population DESC NULLS LAST LIMIT 1) AS gid_en,
    (SELECT z.geonameid FROM _gz z
       WHERE z.country_code=t.cc AND z.nkey = lower(regexp_replace(unaccent(t.en),'[^a-z0-9]','','g'))
       ORDER BY z.population DESC NULLS LAST LIMIT 1) AS gid_exact
  FROM _tf t
),
c AS (
  SELECT slug, tid, iata, COALESCE(gid_ru,gid_en,gid_exact) AS gid,
    ( (gid_ru    IS NOT NULL AND gid_ru   = COALESCE(gid_ru,gid_en,gid_exact))::int
    + (gid_en    IS NOT NULL AND gid_en   = COALESCE(gid_ru,gid_en,gid_exact))::int
    + (gid_exact IS NOT NULL AND gid_exact= COALESCE(gid_ru,gid_en,gid_exact))::int ) AS conf
  FROM r
)
SELECT DISTINCT ON (c.gid) c.gid AS geonameid, c.slug, c.tid, c.iata, g2.name AS name_en
FROM c JOIN public.geo_gazetteer g2 ON g2.geonameid = c.gid
WHERE c.gid IS NOT NULL AND c.conf >= 2
ORDER BY c.gid, g2.population DESC NULLS LAST;

UPDATE public.cities c
   SET tripster_slug = x.slug, tripster_id = x.tid
  FROM _res x
 WHERE c.geonameid = x.geonameid;

INSERT INTO public.cities (geonameid, name_en, iata_code, tripster_slug, tripster_id)
SELECT x.geonameid, x.name_en, x.iata, x.slug, x.tid
  FROM _res x
 WHERE NOT EXISTS (SELECT 1 FROM public.cities c WHERE c.geonameid = x.geonameid);
