-- TRIP-248: drop the now-dead get_ai_usage_cursor() RPC.
--
-- Background: AI usage logging moved off the polling model. The old "AI Usage Logger"
-- n8n workflow (BAHdKa77RpeB5D3O) scanned executions and read a high-water-mark cursor
-- from this RPC. It has been replaced by the "AI Usage save" sub-workflow, which each
-- AI flow calls with its own execution_id (push per execution). get_ai_usage_cursor()
-- was the poller's sole caller and is now unreferenced.
--
-- Kept: ai_usage_events (the sub-workflow still inserts here) and compute_ai_usage_cost()
-- (the cost trigger still fires on insert).
drop function if exists public.get_ai_usage_cursor();
